### ISSUE TITLE
出现这个问题

### ISSUE THREAD

**Issue by yundequanshi** [limxing/Android-PromptDialog#8]
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3552)
	at android.view.View.updateDisplayListIfDirty(View.java:16183)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3751)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3731)
	at android.view.View.updateDisplayListIfDirty(View.java:16151)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3751)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3731)
	at android.view.View.updateDisplayListIfDirty(View.java:16151)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:787)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3071)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2877)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2483)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1494)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6977)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:883)
	at android.view.Choreographer.doCallbacks(Choreographer.java:689)
	at android.view.Choreographer.doFrame(Choreographer.java:624)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:869)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:159)
	at android.app.ActivityThread.main(ActivityThread.java:6326)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)

**Comment by YandZD** [comment]
me.leefeng.promptlibrary.PromptDialog:165
decorView.removeView(promptView);
改为
new Handler().post(new Runnable() {
                            @Override
                            public void run() {
                                decorView.removeView(promptView);
                            }
                        });

**Comment by MyronHaha** [comment]
怎么改呢

**Comment by linruiand** [comment]
同样遇到了这个问题
